import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Heading from "@/components/sections/heading";
import Footer from "@/components/sections/footer";
import CopyRight from "@/components/sections/copy-right";
import TextDrop from "@/components/sections/text-drop";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Heading />
        {children}
        <TextDrop />
        <Footer />
        <CopyRight />
      </body>
    </html>
  );
}
