import type { Metadata } from "next";
// import "../public/fonts/fonts.css"
import { Inter } from "next/font/google";
import "./globals.css";
import Heading from "@/components/sections/heading";
import Footer from "@/components/sections/footer";
import CopyRight from "@/components/sections/copy-right";
import TextDrop from "@/components/sections/text-drop";

import Futura from "@/lib/customFonts";
import { ToasterProvider } from "@/providers/toast-provider";

export const metadata: Metadata = {
  title: "Wonders Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // className={inter.className}
        className={`${Futura.variable}`}
      >
        <ToasterProvider />
        <Heading />
        {children}
        <TextDrop />
        <Footer />
        <CopyRight />
      </body>
    </html>
  );
}
